Repository ddok-ddak/be-ddokddak, pull requests merged in 2023-01, with the labels that each got.

#10 DD-28 카테고리 수정, 삭제 로직 및 테스트 추가
  src/main/java/com/ddokddak/category/api/CategoryController.java
  src/main/java/com/ddokddak/category/dto/CategoryModifyRequest.java
  src/main/java/com/ddokddak/category/dto/CategoryModifyResponse.java
  src/main/java/com/ddokddak/category/dto/CategoryRelationModifyRequest.java
  src/main/java/com/ddokddak/category/dto/CategoryValueModifyRequest.java
  src/main/java/com/ddokddak/category/entity/Category.java
  src/main/java/com/ddokddak/category/repository/CategoryRepository.java
  src/main/java/com/ddokddak/category/service/CategoryWriteService.java
  src/main/java/com/ddokddak/common/exception/NotValidRequestException.java
  src/main/java/com/ddokddak/common/exception/type/NotValidRequest.java
  src/main/java/com/ddokddak/member/repository/MemberRepository.java
  src/test/java/com/ddokddak/category/api/CategoryControllerTest.java
  src/test/java/com/ddokddak/category/api/CategoryIntegrationTest.java
  src/test/java/com/ddokddak/category/fixture/CategoryFixture.java
  src/test/java/com/ddokddak/category/service/CategoryWriteServiceTest.java
Labels: feature

#9 리드미와 로컬용 도커 컴포즈 파일 등 추가
  .github/pull_request_template.md
  Dockerfile
  README.md
  docker-compose-local.yml
Labels: feature

#11 docker hub 사용으로 인한 수정
  .dockerignore
  README.md
  docker-compose-local.yml
Labels: fix

#13 리드미 파일 및 주석 수정
  README.md
  docker-compose-local.yml
Labels: documentation

#12 DD-27 시간 소비 분류 수정 / 삭제 rest docs 작성
  src/docs/asciidoc/category.adoc
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/category.html
  src/main/resources/static/docs/index.html
  src/test/java/com/ddokddak/category/api/CategoryControllerTest.java
  src/test/java/com/ddokddak/category/api/CategoryIntegrationTest.java
Labels: feature

#15 공통 커스텀 예외 코드 관련 수정
  src/main/java/com/ddokddak/common/exception/NotValidRequestException.java
  src/main/java/com/ddokddak/common/exception/type/ExceptionType.java
  src/main/java/com/ddokddak/common/exception/type/NotValidRequest.java
Labels: fix

#17 DD-2 카테고리 조회 로직 수정
  .gitignore
  src/main/java/com/ddokddak/category/api/CategoryController.java
  src/main/java/com/ddokddak/category/dto/CategoryReadResponse.java
  src/main/java/com/ddokddak/category/entity/Category.java
  src/main/java/com/ddokddak/category/repository/CategoryRepository.java
  src/main/java/com/ddokddak/category/service/CategoryReadService.java
  src/main/java/com/ddokddak/common/exception/ExceptionType.java
  src/main/java/com/ddokddak/common/exception/type/NotValidRequest.java
  src/main/resources/data.sql
Labels: feature

#21 [DD-3] 테스트코드 수정 반영
  src/test/java/com/ddokddak/category/service/CategoryWriteServiceTest.java
Labels: fix
